# Generated by Django 5.0.6 on 2024-05-30 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_at',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='created_at',
            new_name='create_date',
        ),
    ]
